language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  
notifications:
  email:
    recipients:
      - dev@jakeleboeuf.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: change
    
before_install:
  - wget http://pear.phpunit.de/get/phpunit.phar
  - chmod +x phpunit.phar